################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: false

## Static configuration
serversTransport:
  insecureSkipVerify: true

################################################################
# Entrypoints configuration
################################################################
entryPoints:
  web:
    address: ':80'
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
    #       permanent: true
    #       priority: 10

  websecure:
    address: ':443'

################################################################
# Traefik logs configuration
################################################################
log:
  level: DEBUG # ERROR # DEBUG
  filePath: /data/logs/traefik.json
  format: json

################################################################
# Access logs configuration
################################################################
accessLog:
  filepath: /data/logs/access.json
  format: json
  bufferingsize: 100

################################################################
# API and dashboard configuration
################################################################
api:
  dashboard: true
  insecure: true

################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    useBindPortIP: true
    exposedByDefault: false
  file:
    filename: middlewares.yml
    directory: /conf/dynamic
    watch: true
    debugLogGeneratedTemplate: true

################################################################
# Certificate resolvers configuration
################################################################
certificatesResolvers:
  hetzner01:
    acme:
      email: 'support@huber.host'
      storage: /data/letsencrypt/hetzner01.json
      dnsChallenge:
        provider: hetzner

