################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: false

################################################################
# Entrypoints configuration
################################################################
entryPoints:
  web:
    address: ':80'
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
    #       permanent: true
    #       priority: 10

  websecure:
    address: ':443'

  ssh-gitea:
    address: ':30'

  # mail-imap-secure:
  #   address: ':993'

  # mail-imap:
  #   address: ':143'

  # mail-pop3-secure:
  #   address: ':995'

  # mail-pop3:
  #   address: ':110'

  # mail-smtp:
  #   address: ':25'

  # mail-smtp-secure:
  #   address: ':465'

  # mail-smtp-secure-2:
  #   address: ':587'

  # mail-sieve:
  #   address: ':4190'

################################################################
# Traefik logs configuration
################################################################
log:
  level: DEBUG # ERROR # DEBUG
  filePath: /data/logs/traefik.json
  format: json

################################################################
# Access logs configuration
################################################################
accessLog:
  filepath: /data/logs/access.json
  format: json
  bufferingsize: 100

################################################################
# API and dashboard configuration
################################################################
api:
  dashboard: true
  insecure: true

################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    useBindPortIP: true
    exposedByDefault: false
  file:
    filename: middlewares.yml
    directory: /conf/dynamic
    watch: true
    debugLogGeneratedTemplate: true

################################################################
# Certificate resolvers configuration
################################################################
certificatesResolvers:
  hetzner01:
    acme:
      email: 'support@huber.host'
      storage: /data/letsencrypt/hetzner01.json
      dnsChallenge:
        provider: hetzner

